# Title shown in Application Information tab.
title: DataStax Enterprise
# Sub Title shown in Application Information tab.
description: Terraform deployment of DSE
schemaVersion: 1.1.0
version: "20190304"

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
#"variables used internally - not exposed to end user"
      - tenancy_ocid
      - region
      - compartment_ocid
      - images

  - title: "Compute Configuration"
    variables:
      - node_shape
      - node_count
      - ssh_public_key
      - dse_version
      - password


######################################################
##############          VARIABLES        #############
######################################################

variables:
  # Hidden variables

######################################################
##############    HIDDEN VARIABLES       #############
######################################################


  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compute Compartment
    description: The compartment in which to create all Compute resources
    default: compartment_ocid

######################################################
##############    COMPUTE VARIABLES      #############
######################################################

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: Public SSH Key string
    description: Public SSH Key to access VM via SSH

  node_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.2
    title: Node Shape
    required: true
    dependsOn:
      compartmentId: compartment_ocid

  node_count:
    type: integer
    default: 3
    title: Number of DSE nodes
    minimum: 1

  dse_version:
    type: enum
    title: DSE Version
    enum:
      - "6.8.6"
      - "6.8.5"
      - "6.8.4"
      - "6.8.3"
      - "6.8.2"
      - "6.8.1"
      - "6.8.0"
      - "6.7.12"
      - "6.7.11"
    required: true
    default: "6.8.6"

  password:
    type: password
    title: "Password for DSE user 'cassandra' and OpsCenter user 'admin'"
    description: "Alphanumeric, min 8 characters"
    required: true
    pattern: "^[a-zA-Z0-9]{8,}$"


#############################################
##############     OUTPUTS     ##############
#############################################

outputs:
  opscenter_url:
    type: link
    title: "OpsCenter URL"
    visible: true

  lifecyclemanager_url:
    type: link
    title: "Life Cycle Manager URL"
    visible: true

  node_public_ips:
    type: copyableString
    title: "Node public IPs"
    visible: true

  node_private_ips:
    type: copyableString
    title: "Node private IPs"
    visible: true
